[workspace]

members = [
    "src/http_proxy",
    "src/ledger",
    "src/kvstore",
    "src/omni-abci",
    "src/omni-echo",
    "src/omni-ledger",
    "src/omni-module",
    "src/omni-kvstore",
]

# Uncomment this for local builds of minicose.
#[patch."https://github.com/l-1-labs/rust-minicose"]
#minicose = { path = "../rust-minicose" }

#[patch."ssh://git@github.com/l-1-labs/omni-rust.git"]
#omni = { path = "../omni-rust" }
