[workspace]

members = [
    "ledger",
    "omni",
    "omni-abci",
    "omni-echo",
    "omni-ledger",
]

# Uncomment this for local builds of minicose.
#[patch."https://github.com/l-1-labs/rust-minicose"]
#minicose = { path = "../rust-minicose" }
