[workspace]

members = [
    "src/http_proxy",
    "src/ledger",
    "src/kvstore",
    "src/omni",
    "src/omni-abci",
    "src/omni-echo",
    "src/omni-ledger",
    "src/omni-kvstore",
]

# Uncomment this for local builds of minicose.
#[patch."https://github.com/l-1-labs/rust-minicose"]
#minicose = { path = "../rust-minicose" }
