[package]
name = "omni-echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
clap = "3.0.0-beta.5"
omni = { path = "../omni", features = [ "pem" ] }
pem = "1.0.0"
