version: '3'

services:
  abci-0:
    image: "omni/abci"
    ports:
      - "8000:8000"
      - "26658:26658"
    volumes:
      - ./genfiles/node0:/node0:ro
    command:
      - --omni
      - 0.0.0.0:8000
      - --omni-app
      - http://ledger-0:8000
      - --omni-pem
      - /node0/abci.pem
      - --abci
      - 0.0.0.0:26658
      - --tendermint
      - http://tendermint-0:26657/
    depends_on:
      - ledger-0
    networks:
      frontend:
        ipv4_address: 172.16.1.10
  #    networks:
#      frontend:
#      node0-net:
  ledger-0:
    image: "omni/ledger"
    ports:
      - "8001:8000"
    volumes:
      - ./genfiles/node0/persistent-ledger:/persistent
      - ./genfiles/node0:/node0:ro
    command:
      - -v
      - -v
      - --abci
      - --addr
      - 0.0.0.0:8000
      - --state
      - /node0/ledger_state.json
      - --persistent
      - /persistent/ledger.db
      - --pem
      - /node0/ledger.pem
    networks:
      frontend:
        ipv4_address: 172.16.1.11
#    networks:
#      node0-net:
  tendermint-0:
    image: "tendermint/tendermint:v0.35.1"
    command:
      - --log-level
      - trace
      - node
      - --proxy-app
      - tcp://abci-0:26658
    ports:
      - "26600:26600"
    depends_on:
      - abci-0
    volumes:
      - ./genfiles/node0/tendermint:/tendermint:Z
    networks:
      frontend:
        ipv4_address: 172.16.1.12
#    networks:
#      tendermint-net:
#      node0-net:

#networks:
#  frontend:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.20.0.0/24
#  tendermint-net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.20.1.0/24
#  node0-net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.20.100.0/24

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
